enableSpaceControl = true
showSpaceControl = 'cmd+opt+space'
showMenuBarIcon = false
showMenuBarTitle = true
menuBarTitleTemplate = '[$WORKSPACE]'

enableIntegrations = true
runScriptAfterWorkspaceChange = 'open -g "hammerspoon://tile-now"'
