[tools]
node = "22"
pnpm = "latest"
"npm:@meza/adr-tools" = "latest"
"npm:tsx" = "latest"
"npm:wrangler" = "latest"
awscli = { version = "latest", symlink_bins = "true" }

[settings]

[settings.npm]
package_manager = "pnpm"
